all:
	cd omok;     make all
	cd test;     make all
	cd tpstest;  make all
install:
	cd omok;     make install
	cd test;     make install
	cd tpstest;  make install
clean:
	cd omok;     make clean
	cd test;     make clean
	cd tpstest;  make clean
